# Generated by Django 4.2.17 on 2025-01-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JiraInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Instance Name')),
                ('base_url', models.URLField(verbose_name='Base URL')),
                ('api_version', models.CharField(max_length=20, verbose_name='API Version')),
                ('auth_token', models.CharField(max_length=500, verbose_name='Auth Token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Jira Instance',
                'verbose_name_plural': 'Jira Instances',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20, verbose_name='Project ID')),
                ('key', models.CharField(max_length=20, verbose_name='Project Key')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('configuration_snapshot', models.JSONField(verbose_name='Configuration Snapshot')),
                ('last_sync', models.DateTimeField(verbose_name='Last Sync')),
                ('jira_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.jirainstance', verbose_name='Jira Instance')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'unique_together': {('jira_instance', 'project_id')},
            },
        ),
        migrations.CreateModel(
            name='DocumentationExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('md', 'Markdown'), ('json', 'JSON'), ('yaml', 'YAML')], max_length=20, verbose_name='Format')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('file_path', models.CharField(max_length=500, verbose_name='File Path')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='core.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Documentation Export',
                'verbose_name_plural': 'Documentation Exports',
            },
        ),
        migrations.CreateModel(
            name='ConfigurationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('configuration_type', models.CharField(max_length=50, verbose_name='Configuration Type')),
                ('data', models.JSONField(verbose_name='Configuration Data')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Configuration Snapshot',
                'verbose_name_plural': 'Configuration Snapshots',
            },
        ),
    ]
