# Generated by Django 4.2.17 on 2025-01-11 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_project_configuration_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_export_format', models.CharField(choices=[('html', 'HTML'), ('pdf', 'PDF'), ('md', 'Markdown')], default='html', max_length=10, verbose_name='Default Export Format')),
                ('auto_sync_enabled', models.BooleanField(default=False, verbose_name='Auto-sync Enabled')),
                ('sync_interval', models.IntegerField(default=60, help_text='How often to sync projects (in minutes)', verbose_name='Sync Interval (minutes)')),
                ('default_jira_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_settings', to='core.jirainstance', verbose_name='Default Jira Instance')),
            ],
            options={
                'verbose_name': 'Application Settings',
                'verbose_name_plural': 'Application Settings',
            },
        ),
    ]
