# Generated by Django 4.2.17 on 2025-01-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_applicationsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documentation_url',
            field=models.URLField(blank=True, help_text='URL to external project documentation (e.g., Confluence)', max_length=500, null=True, verbose_name='Documentation URL'),
        ),
    ]
