# Generated by Django 4.2.17 on 2025-01-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_project_documentation_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jirainstance',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Sync'),
        ),
    ]
