# Generated by Django 4.2.17 on 2025-01-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jirainstance_last_sync'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jirainstance',
            options={'ordering': ['name'], 'verbose_name': 'Jira Instance', 'verbose_name_plural': 'Jira Instances'},
        ),
        migrations.RemoveField(
            model_name='jirainstance',
            name='api_version',
        ),
        migrations.RemoveField(
            model_name='jirainstance',
            name='auth_token',
        ),
        migrations.AddField(
            model_name='jirainstance',
            name='api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jirainstance',
            name='username',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='jirainstance',
            name='base_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='jirainstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jirainstance',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jirainstance',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jirainstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
