# Generated by Django 4.2.17 on 2025-01-14 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_jirainstance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentationexport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='documentationexport',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='documentationexport',
            name='generated_at',
        ),
        migrations.AddField(
            model_name='documentationexport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='documentationexport',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentationexport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='exports/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='documentationexport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentationexport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentationexport',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('xml', 'XML')], max_length=10),
        ),
        migrations.AlterField(
            model_name='documentationexport',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='core.project'),
        ),
    ]
