# Generated by Django 4.2.17 on 2025-02-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_instance_type'),
        ('core', '0007_alter_documentationexport_options_and_more'),
    ]

    operations = [
    ]
